; Database Configuration
[ProductionMode]
mode = 0

[centerline]
wide_lane_width_start = 550
wide_lane_width_end = 350
wide_lane_width_step = 50
merge_lane_start_width = 200
merge_lane_end_width = 100
split_lane_start_width = 100
split_lane_end_width = 250
virtual_merge_end_width = 400
virtual_split_start_width = 400
offset_line_width = 175
lane_offset_step_length = 5000
car_offset_split = 8000
bev_max_offset = 15000


[lanefusion]
k_EFM_enable_intersection_topology = 0
